caption=Advanced settings
max_units=Max units:
starting_units=Starting units:
max_buildings=Max buildings:
ships=Boats
ships_tip=Allow ships in this game
reset_defaults=Reset to defaults
performance_warning=Values above the defaults can degrade performance.
