cinematic_on=Cinematic camera on
cinematic_off=Cinematic camera off
spectator_following=Spectating - 
spectator_free=Free camera
spectator_next=Next - {0}
spectator_previous=Previous - {0}
spectator_free_cam=Free cam / follow - {0}
spectator_exit=Exit - Esc
