observer_mode=Observer Mode - Press escape to exit
observer_following=Observing {0}   [ ] switch player   Backslash free camera   Esc exit
observer_free=Observer free camera   [ ] follow a player   Esc exit
